version: "3.8"
name: mysqldb
services:
  mysqldb_order:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=order-service
      - MYSQL_USER=longhd
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
  mysqldb_inventory:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=inventory-service
      - MYSQL_USER=longhd
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
